spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: test
    password: test
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  profiles:
    active: dev
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  file:
    path: d:/
server:
  port: 8082